// Generated by https://quicktype.io
export interface PokemonResponse {
  count: number;
  next: string;
  previous: null;
  results: Result[];
}

export interface Result {
  pokemonNumber?: number;
  name: string;
  url: string;
}
